### ISSUE TITLE
forgeessentials player logger error

### ISSUE THREAD

**Issue by scootashy** [ForgeEssentials/ForgeEssentialsMain#1310]
seems when trying to do a lookup on block changes it throws errors in console and only shows numbers in chat. I had the host look into it in case there database server setup wasnt working right. they said all seemed ok and that it was saying the playername was too big. So I'm posting here about it incase its a bug or a useraccount name limit that maybe should be increased since there is quite a few minecraft accounts with longer names. mine is scootashydash.

here's the log that has the thrown error about the player data too long error.

https://www.dropbox.com/s/k7swhcus9ki70nc/fml-server-latest%281%29.log?dl=0

**Comment by helinus** [comment]
This is most likely a dupe of #1254 and that was fixed in build 401, you are on build 397.

**Comment by scootashy** [comment]
ok so I have to update playerlogger to 401 since the version i have came with forgeessentials beta5 the latest

**Comment by helinus** [comment]
Just get the latest version of FE from our jenkins: http://176.9.50.214:8080/job/ForgeEssentials/

**Comment by scootashy** [comment]
ok just did and ran it. loaded up but still throws player data too long errors is there a setting to it or such somewhere where I can change the limit to allow the longer uuid and playernames?

**Comment by helinus** [comment]
You can either drop the whole payerlogger sql table and let FE recreate it or change the player field from VARCHAR(32) to VARCHAR(255) with whatever sql tool you prefer.

**Comment by scootashy** [comment]
I just seen that a bit ago and fixed it. it seems to be logging now. cept I have to place a block where a block was broke at for it to show the break change for some reason. if I try to rollback it doesnt do anything or it says an unknown internal error occured. and i got this in the console
https://www.dropbox.com/s/ozjecskqqm8xzjk/Screenshot%202015-02-25%2011.18.09.png?dl=0

https://www.dropbox.com/s/8tzq9g63hbxmow2/Screenshot%202015-02-25%2011.18.19.png?dl=0

**Comment by scootashy** [comment]
its working now and i wont be doing much with the rollback system since I seen there is gonna be a rewrite on the playerlogger. will it also be updated to convert the displayed uuids to usernames when a lookup is done?
