### ISSUE TITLE
Need help with disableing gamemode please on ForgeEssentials

### ISSUE THREAD

**Issue by rodnico2681** [ForgeEssentials/ForgeEssentialsMain#1655]
Olee could you pleast type in the line I would have to type to disable creative mode for the players in my server, I went through the tutorial and I tried different ways but I cant seem to understand what I am doing wrong. I have checked the wiki, google, youtube, and I am embarrassed to say it but could you please show me how to write the line to disable creative. Thank You.

**Comment by olee** [comment]
What exactly do you want to do?
- Is your server gamemode set to survival / creative?
- Did you try `/gamemode creative <player>`?
- Is your problem possibly that players are able to use `/gamemode` by themselves?  
  (Permission issue?)

**Comment by rodnico2681** [comment]
yes, the players are able to immediately use gamemode and change their survival to creative

**Comment by rodnico2681** [comment]
its a server where my family plays, all of our kids get on and we don't want them accessing the /gamemode creative function, when they log on even if its their first time on, they are able to /gamemode 1 and go into creative, I could use some help in disableing that please, i'm not that good with writing permissions.

**Comment by olee** [comment]
Update to latest version.
This issue has been fixed a few hours ago.

**Comment by olee** [comment]
Please download [this](http://minecraft.curseforge.com/mc-mods/74735-forge-essentials-74735/files/2249239) release from a few hours ago. Also if you didn't do it yet, delete the `world/FEData/permissions` folder once.

If this still does not work, I suggest you try creating a small new server for testing with only FE and see if it works. Maybe you just grabbed the wrong build which is why it didn't work.

Also try this:
- Use `/p debug`
- Use `/op`
- Check if it shows `command.op` somewhere in the chat

**Comment by rodnico2681** [comment]
I did them both, the /p debug just said that debug mode is on. the command.op = false zone  [root] and then group  [ _All_ ] players are still able to just type /gamemode and switch their gamemode.

**Comment by olee** [comment]
If it showed `command.op = false`, then it should also have shown you "You are not allowed to use this command". If other players are still able to use that command, this means they probably have given themselves OP status already and you just need to `/deop` them.

You can remove all OPs like that:
- Stop your server
- Delete (or modify) `ops.json` file in your server directory
- Restart server

Because you got the `command.op = false` message when using `/p debug`, this means the permissions definitely work correctly and this is just a configuration issue.

**Comment by rodnico2681** [comment]
so I removed the ops.json file and ran the server again, the problem persists, I haven't written anything else since I mentioned my problem to you, been following your instructions and I really don't know why they can access gamemode command by just typing /gamemode, they don't even have to type in the 1, by just typing /gamemode again it toggles between creative and survival. don't know if that helps you identify whats going on, thought i'd mention it.

**Comment by rodnico2681** [comment]
when I type /deop on the players who show me they can do it, its says could not de-op <player>

**Comment by olee** [comment]
Toggling gamemode with just `/gamemode` or `/gm` is a default ForgeEssentials feature.
Could you maybe join me on [IRC](http://webchat.esper.net/?channels=forgeessentials&prompt=1)?
This would make investigating this problem a bit easier.

**Comment by rodnico2681** [comment]
sure
