### ISSUE TITLE
Unable to disable bow use even with right permission

### ISSUE THREAD

**Issue by TigerRampage** [ForgeEssentials/ForgeEssentialsMain#1732]
Even after setting fe.protection.use.minecraft.bow.* to false in the server, players can still use bows. While this permission works correctly with any other item, it does not with bows. This is an issue as one mod in my server adds new types of arrows that spread fire and such, and I would like to disable bows in the spawn area so no issues occur.

I am using the following command with no luck. It functions fine with all other permissions.
/p group [group] zone [zone] false fe.protection.use.item.bow.*

If I made a mistake, please let me know. Also, this is Minecraft 1.7.10. Thank you for your time.

![bow_still_works](https://cloud.githubusercontent.com/assets/2359031/9721851/b9c2edac-5570-11e5-8109-927f8908206e.png)

**Comment by olee** [comment]
Actually this is not true.
It just **looks** like the bow can still be used for the client.
On the server, it will never actually shoot an arrow.
You can try it out yourself if you check the number of arrows you have (non creative), shoot one and move the arrow stack in your inventory or reconnect to the server.

Anyway this was fixed in https://github.com/ForgeEssentials/ForgeEssentialsMain/commit/f9ab5ab6b3984605a05b137226140e44f26f824f but it needs the client mod to work (sorry, no other way to prevent this desync with the client otherwise).

**Comment by TigerRampage** [comment]
Hi, thank you for taking the time to look into this and for your response. Unfortunately, even after updating to the version listed above, we are still having this bug, and it is more than a de-sync for us. While it sometimes works as you mentioned (the arrow will eventually return to my inventory), it usually shoots the arrow and does not return. Other players are then able to pick-up the arrow and have it in their inventory. We tried re-logging into the server to fix the error with no success.

I checked to make sure the correct permission is set for the correct group and zone. If you need any more details, I am more than willing to provide some. Thank you again.

**Comment by olee** [comment]
Try again with `/p debug` enabled and see if it really denies the use-permission.

Also: Are you using the default minecraft bow? Or some modded item? You could also try it with food.
Also it looks like you did not add the client mod, because it would even stop you from being able to charge the bow (if you can charge the bow with denied permission, you don't have the (correct) FE client mod).
